# Generated by Django 5.2.8 on 2025-11-28 06:26

import django.db.models.deletion
import investor_posts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorPost',
            fields=[
                ('id', models.CharField(default=investor_posts.models.gen_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('stages', models.JSONField(blank=True, default=list)),
                ('amount_range', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('contact_preference', models.CharField(default='email', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='investor/logos/')),
                ('views', models.IntegerField(default=0)),
                ('saved_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedInvestorPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_investor_posts', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor_posts.investorpost')),
            ],
            options={
                'unique_together': {('developer', 'post')},
            },
        ),
    ]
