# Generated by Django 5.2.8 on 2025-11-28 06:26

import django.db.models.deletion
import requests_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investor_posts', '0001_initial'),
        ('pitches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.CharField(default=requests_app.models.gen_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('meeting_link', models.TextField(blank=True, null=True)),
                ('preference', models.CharField(choices=[('email', 'email'), ('phone', 'phone'), ('dm', 'dm')], default='email', max_length=10)),
                ('viewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('investor_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investor_posts.investorpost')),
                ('pitch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pitches.pitch')),
            ],
        ),
    ]
