# Generated by Django 5.2.8 on 2025-12-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='meeting_ended_at',
            field=models.DateTimeField(blank=True, help_text='Actual time when meeting ended', null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='meeting_started_at',
            field=models.DateTimeField(blank=True, help_text='Actual time when meeting started', null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='meeting_status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='meeting_summary',
            field=models.TextField(blank=True, help_text='Generated summary of the meeting', null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='scheduled_end_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled end time for the meeting', null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='scheduled_start_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled start time for the meeting', null=True),
        ),
    ]
