# Generated by Django 5.2.8 on 2025-12-13 10:07

import django.db.models.deletion
import requests_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_contactrequest_meeting_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='agenda',
            field=models.TextField(blank=True, help_text='Meeting agenda or discussion topics', null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='meeting_platform',
            field=models.CharField(blank=True, choices=[('google-meet', 'Google Meet'), ('zoom', 'Zoom'), ('microsoft-teams', 'Microsoft Teams'), ('phone', 'Phone Call'), ('in-person', 'In-Person'), ('other', 'Other')], default='google-meet', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Timezone for the meeting (e.g., America/New_York)', max_length=50),
        ),
        migrations.CreateModel(
            name='MeetingSummary',
            fields=[
                ('id', models.CharField(default=requests_app.models.gen_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('discussion_points', models.JSONField(default=list, help_text='List of key discussion points')),
                ('action_items', models.JSONField(default=list, help_text='List of action items with assignee and due date')),
                ('decisions_made', models.JSONField(default=list, help_text='List of decisions made during meeting')),
                ('next_steps', models.TextField(blank=True, help_text='Overall next steps and follow-up plan', null=True)),
                ('needs_followup', models.BooleanField(default=False)),
                ('followup_date', models.DateTimeField(blank=True, help_text='Proposed follow-up meeting date', null=True)),
                ('additional_notes', models.TextField(blank=True, help_text='Any additional notes or observations', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structured_summary', to='requests_app.contactrequest')),
            ],
        ),
    ]
