# Generated by Django 5.2.8 on 2025-11-28 06:26

import django.db.models.deletion
import pitches.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.CharField(default=pitches.models.gen_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=300)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('funding_stage', models.CharField(blank=True, max_length=30)),
                ('ask', models.CharField(blank=True, max_length=150)),
                ('video', models.FileField(upload_to='pitches/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='pitches/thumbnails/')),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedPitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_pitches', to=settings.AUTH_USER_MODEL)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitches.pitch')),
            ],
            options={
                'unique_together': {('investor', 'pitch')},
            },
        ),
    ]
