# Generated by Django 5.2.8 on 2025-12-14 18:52

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0002_alter_pitch_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='video',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='pitches/videos/'),
        ),
    ]
